-------------------------------------------------------------------
# Collaborative Filtering

## User based filtering
measure the similarity between target users and other users

In [1]:
import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

In [2]:
book_df = pd.read_csv('./Books.csv', low_memory=False)
ratings_df = pd.read_csv('./Ratings.csv').sample(4000)
user_df = pd.read_csv('./Users.csv')
user_rating_df = ratings_df.merge(user_df, left_on = 'User-ID', right_on = 'User-ID')

In [3]:
book_user_rating = book_df.merge(user_rating_df, left_on = 'ISBN',right_on = 'ISBN')
book_user_rating = book_user_rating[['ISBN', 'Book-Title', 'Book-Author', 'User-ID', 'Book-Rating']]
book_user_rating.reset_index(drop=True, inplace = True)

d ={}
for i,j in enumerate(book_user_rating.ISBN.unique()):
    d[j] =i
book_user_rating['unique_id_book'] = book_user_rating['ISBN'].map(d)

users_books_pivot_matrix_df = book_user_rating.pivot(index='User-ID', 
                                                          columns='unique_id_book', 
                                                          values='Book-Rating').fillna(0)

users_books_pivot_matrix_df.head()


users_books_pivot_matrix_df = users_books_pivot_matrix_df.values
users_books_pivot_matrix_df




array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [4]:
book_user_rating = book_df.merge(user_rating_df, left_on = 'ISBN',right_on = 'ISBN')
book_user_rating = book_user_rating[['ISBN', 'Book-Title', 'Book-Author', 'User-ID', 'Book-Rating']]
book_user_rating.reset_index(drop=True, inplace = True)

In [5]:
d ={}
for i,j in enumerate(book_user_rating.ISBN.unique()):
    d[j] =i
book_user_rating['unique_id_book'] = book_user_rating['ISBN'].map(d)

In [6]:
users_books_pivot_matrix_df = book_user_rating.pivot(index='User-ID', 
                                                          columns='unique_id_book', 
                                                          values='Book-Rating').fillna(0)

In [7]:
users_books_pivot_matrix_df.head()


unique_id_book  0     1     2     3     4     5     6     7     8     9     \
User-ID                                                                      
99               0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   
232              0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   
507              0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   
625              0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   
638              0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   

unique_id_book  ...  3354  3355  3356  3357  3358  3359  3360  3361  3362  \
User-ID         ...                                                         
99              ...   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   
232             ...   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   
507             ...   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   
625             ...   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   
638             ...   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   

unique_id_book  3363  
User-ID               
99               0.0  
232              0.0  
507              0.0  
625              0.0  
638              0.0  

[5 rows x 3364 columns]

In [8]:
users_books_pivot_matrix_df = users_books_pivot_matrix_df.values
users_books_pivot_matrix_df

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [9]:
pip install scipy

Note: you may need to restart the kernel to use updated packages.


In [10]:
from scipy.sparse.linalg import svds

NUMBER_OF_FACTORS_MF = 15

#Performs matrix factorization of the original user item matrix
U, sigma, Vt = svds(users_books_pivot_matrix_df, k = NUMBER_OF_FACTORS_MF)

In [11]:
sigma = np.diag(sigma)
sigma.shape

(15, 15)

In [12]:
all_user_predicted_ratings = np.dot(np.dot(U, sigma), Vt) 
all_user_predicted_ratings

array([[ 1.51321481e-31,  1.76032408e-46,  1.50722452e-32, ...,
         0.00000000e+00,  0.00000000e+00, -8.90585137e-33],
       [ 6.91352149e-34, -4.11836668e-49,  4.14677690e-35, ...,
         0.00000000e+00,  0.00000000e+00, -2.94248719e-35],
       [ 3.16433247e-32,  3.40393525e-47, -5.35632140e-33, ...,
         0.00000000e+00,  0.00000000e+00,  2.18892948e-32],
       ...,
       [-2.98945390e-31, -2.45216815e-46, -3.07051187e-32, ...,
         0.00000000e+00,  0.00000000e+00,  1.86140042e-32],
       [-1.95639182e-32, -1.37777163e-47,  3.16459052e-33, ...,
         0.00000000e+00,  0.00000000e+00, -1.24865116e-32],
       [-3.29862152e-31, -6.03463862e-47, -5.51783319e-33, ...,
         0.00000000e+00,  0.00000000e+00,  6.16833317e-32]])

In [13]:
def top_cosine_similarity(data, book_id, top_n=10):
    index = book_id 
    book_row = data[index, :]
    magnitude = np.sqrt(np.einsum('ij, ij -> i', data, data))
    similarity = np.dot(book_row, data.T) / (magnitude[index] * magnitude)
    sort_indexes = np.argsort(-similarity)
    return sort_indexes[:top_n]

def similar_books(book_user_rating, book_id, top_indexes):
    print('Recommendations for {0}: \n'.format(
    book_user_rating[book_user_rating.unique_id_book == book_id]['Book-Title'].values[0]))
    for id in top_indexes + 1:
        print(book_user_rating[book_user_rating.unique_id_book == id]['Book-Title'].values[0])

In [14]:
k = 50
movie_id =25954  
top_n = 3
sliced = Vt.T[:, :k] # representative data

similar_books(book_user_rating, 25954, top_cosine_similarity(sliced, movie_id, top_n))

IndexError: index 25954 is out of bounds for axis 0 with size 3364

## Item based filtering

Measuring the similarity between the books that users rates with and other users books ratings

## Single Value- / UV-Decomposition